---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - make build

- name: test
  image: golang
  commands:
  - make test 

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN

# TODO: deploy
