version: v0

runs:
  - name: Build and test Aryzona
    tasks:
      - name: build
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - clone:
          - restore_cache:
              keys:
                - cache-sum-{{ md5sum "go.sum" }}
                - cache-date-
              ## golang image sets GOPATH to /go
              dest_dir: /go/pkg/mod/cache
          - run:
              name: build aryzona
              command: make build
          - save_to_workspace:
              contents:
                - source_dir: .
                  dest_dir: ./
                  paths:
                    - '**'
      - name: test
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - restore_workspace:
              dest_dir: .
          - run:
              name: test aryzona
              command: make test
          - save_cache:
              key: cache-sum-{{ md5sum "go.sum" }}
              contents:
                - source_dir: /go/pkg/mod/cache
          - save_cache:
              key: cache-date-{{ year }}-{{ month }}-{{ day }}
              contents:
                - source_dir: /go/pkg/mod/cache
        depends:
          - build
