version: v0

runs:
  - name: Aryzona CI

    # Build
    tasks:
      - name: build
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - clone:
          - restore_cache:
              keys:
                - pkg-cache-sum-{{ md5sum "go.sum" }}-{{ year }}-{{ month }}-{{ day }}
              dest_dir: /go/pkg
          - restore_cache:
              keys:
                - build-cache-sum-{{ md5sum "go.sum" }}-{{ year }}-{{ month }}-{{ day }}
              dest_dir: /root/.cache/go-build
          - run:
              name: build
              command:  make build
          - save_to_workspace:
              contents:
                - source_dir: /root/project/
                  dest_dir: /root/project/
                  paths:
                    - '**'
          - save_to_workspace:
              contents:
                - source_dir: /root/.cache/go-build
                  dest_dir: /root/.cache/go-build
                  paths:
                    - '**'
          - save_to_workspace:
              contents:
                - source_dir: /go/pkg
                  dest_dir: /go/pkg
                  paths:
                    - '**'

      # Test
      - name: test
        depends:
          - build
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - restore_workspace:
              dest_dir: /
          - run:
              name: test
              command:  make test
          - save_cache:
              key: pkg-cache-sum-{{ md5sum "go.sum" }}-{{ year }}-{{ month }}-{{ day }}
              contents:
                - source_dir: /go/pkg
          - save_cache:
              key: build-cache-sum-{{ md5sum "go.sum" }}-{{ year }}-{{ month }}-{{ day }}
              contents:
                - source_dir: /root/.cache/go-build

      # Inspect code
      - name: inspect
        depends:
          - build
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - restore_workspace:
              dest_dir: /
          - restore_cache:
              keys:
                - pkg-cache-bin-{{ year }}-{{ month }}
              dest_dir: /go/bin
          - run:
              name: install inspect tools
              command: ./.agola/install_tools.sh
          - run:
              name: inspect
              command:  make inspect 
          - save_cache:
              key: pkg-cache-bin-{{ year }}-{{ month }}
              contents:
                - source_dir: /go/bin
                  paths:
                    - revive
                    - gosec
                    - misspell
                    - staticcheck

      # Deploy (when the branch is Master)
      - name: deploy
        when:
          branch: master
        environment:
          DEPLOY_USER:
            from_variable: deployuser
          DEPLOY_PATH:
            from_variable: deploypath
          DEPLOY_HOST:
              from_variable: deployhost
        depends:
          - test
          - inspect
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - restore_workspace:
              dest_dir: .
          - run:
              name: deploy aryzona assets
              command: scp -B -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./assets $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/
          - run:
              name: deploy aryzona
              command: scp -B -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./aryzona $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/aryzona-new
          - run:
              name: restart bot
              command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$DEPLOY_USER@$DEPLOY_HOST" ary-restart
