version: v0

runs:
  - name: Build and test Aryzona
    tasks:
      - name: build
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - clone:
          - restore_cache:
              keys:
                - pkg-cache-sum-{{ md5sum "go.sum" }}
              dest_dir: /go/pkg
          - restore_cache:
              keys:
                - build-cache-sum-{{ md5sum "go.sum" }}
              dest_dir: ~/.cache/go-build
          - run:
              name: build aryzona
              command: make build 
          - save_to_workspace:
              contents:
                - source_dir: .
                  dest_dir: ./
                  paths:
                    - '**'
                - source_dir: ~/.cache/go-build
                  dest_dir: ~/.cache/go-build
      - name: test
        depends:
          - build
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - restore_workspace:
              dest_dir: .
          - run:
              name: test aryzona
              command: make test
          - save_cache:
              key: pkg-cache-sum-{{ md5sum "go.sum" }}
              contents:
                - source_dir: /go/pkg
          - save_cache:
              key: build-cache-sum-{{ md5sum "go.sum" }}
              contents:
                - source_dir: ~/.cache/go-build
      - name: deploy
        when:
          branch: master
        environment:
          DEPLOY_USER:
            from_variable: deployuser
          DEPLOY_PATH:
            from_variable: deploypath
          DEPLOY_USER:
            from_variable: deployuser
          DEPLOY_HOST:
              from_variable: deployhost
        depends:
          - test
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - restore_workspace:
              dest_dir: .
          - run:
              name: deploy aryzona
              command: scp -B -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./aryzona $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH 
          - run:
              name: restart bot
              command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$DEPLOY_USER@$DEPLOY_HOST" ary-restart
