version: v0

runs:
  - name: Build and test Aryzona
    tasks:
      - name: build and test
        environment:
          DISCORD_WEBHOOK:
            from_variable: discordwebhook
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - clone:
          - restore_cache:
              keys:
                - bin-cache-sum-{{ md5sum "go.sum" }}-{{ year }}-{{ month }}-{{ day }}
              dest_dir: /go/bin
          - restore_cache:
              keys:
                - pkg-cache-sum-{{ md5sum "go.sum" }}-{{ year }}-{{ month }}-{{ day }}
              dest_dir: /go/pkg
          - restore_cache:
              keys:
                - build-cache-sum-{{ md5sum "go.sum" }}-{{ year }}-{{ month }}-{{ day }}
              dest_dir: /root/.cache/go-build
          - run:
              name: install agola-discord
              command: "[ -f /go/bin/agola-discord ] || GO111MODULE=off go get github.com/Pauloo27/agola-discord"
          - run:
              name: build aryzona
              command: agola-discord make build
          - run:
              name: test aryzona
              command: agola-discord make test
          - save_to_workspace:
              contents:
                - source_dir: ./assets
                  paths:
                    - '**'
                  dest_dir: .
                - source_dir: .
                  paths:
                    - 'aryzona'
                  dest_dir: .
          - save_cache:
              key: bin-cache-sum-{{ md5sum "go.sum" }}-{{ year }}-{{ month }}-{{ day }}
              contents:
                - source_dir: /go/bin
          - save_cache:
              key: pkg-cache-sum-{{ md5sum "go.sum" }}-{{ year }}-{{ month }}-{{ day }}
              contents:
                - source_dir: /go/pkg
          - save_cache:
              key: build-cache-sum-{{ md5sum "go.sum" }}-{{ year }}-{{ month }}-{{ day }}
              contents:
                - source_dir: /root/.cache/go-build
      - name: deploy
        when:
          branch: master
        environment:
          DEPLOY_USER:
            from_variable: deployuser
          DEPLOY_PATH:
            from_variable: deploypath
          DEPLOY_USER:
            from_variable: deployuser
          DEPLOY_HOST:
              from_variable: deployhost
        depends:
          - build and test
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - restore_workspace:
              dest_dir: .
          - run:
              name: deploy aryzona assets
              command: scp -B -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./assets $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/
          - run:
              name: deploy aryzona
              command: scp -B -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./aryzona $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/aryzona-new
          - run:
              name: restart bot
              command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$DEPLOY_USER@$DEPLOY_HOST" ary-restart
