package youtube

import (
	"regexp"

	"github.com/kkdai/youtube/v2"
)

var (
	vidDescriptionRe = regexp.MustCompile(`(?s)([^·\n]+)\s?·\s?([^\n]+)\n+([^\n]+)(?:.+?℗\s*(\d{4}))?(?:.+?Released on\s*:\s*(\d{4}-\d{2}-\d{2}))?(?:[^A-Za-z\n]+(?:Artist\s*:\s*))?([^\n]+)?.+\nAuto-generated by YouTube\.\s*$`)
)

type Music struct {
	Track       string
	Artist      string
	Album       string
	ReleaseYear string
	ReleaseDate string
}

func parseDescription(vid *youtube.Video) *Music {
	if vid.Description == "" {
		return nil
	}

	matches := vidDescriptionRe.FindStringSubmatch(vid.Description)
	if len(matches) < 6 {
		return nil
	}

	track := matches[1]
	artist := matches[2]

	if track == "" || artist == "" {
		return nil
	}

	album := matches[3]
	releaseYear := matches[4]
	releaseDate := matches[5]

	return &Music{
		Track:       track,
		Artist:      artist,
		Album:       album,
		ReleaseYear: releaseYear,
		ReleaseDate: releaseDate,
	}
}
